# Generated by Django 3.2.12 on 2022-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='scan_filename',
        ),
        migrations.AddField(
            model_name='specimen',
            name='dropbox_glb_file_path',
            field=models.CharField(blank=True, help_text='path to public link on dropbox for .glb file, only the part after the /s/', max_length=200),
        ),
        migrations.AddField(
            model_name='specimen',
            name='dropbox_ply_file_path',
            field=models.CharField(blank=True, help_text='path to public link on dropbox for full size .ply file, only the part after the /s/', max_length=200),
        ),
    ]
