# Generated by Django 3.2.12 on 2022-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0002_auto_20220410_1741'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skeleton',
            constraint=models.UniqueConstraint(fields=('repository', 'collection_code', 'specimen_number'), name='unique skeleton'),
        ),
    ]
