# Generated by Django 3.2.12 on 2022-04-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0003_skeleton_unique skeleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='skeleton',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
