# Generated by Django 3.2.12 on 2022-09-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0004_skeleton_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='skeleton',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
