# Generated by Django 4.1.6 on 2023-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0005_skeleton_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='DO_spaces_glb_file_path',
            field=models.CharField(blank=True, help_text='path to public link on DO spaces for .glb file', max_length=200),
        ),
    ]
