# Generated by Django 4.1.6 on 2023-04-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0006_specimen_do_spaces_glb_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skeleton',
            name='specimen_number',
            field=models.CharField(max_length=100),
        ),
    ]
