# Generated by Django 4.1.6 on 2023-05-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeletons', '0007_alter_skeleton_specimen_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skeleton',
            old_name='specimen_number',
            new_name='specimen_identifier',
        ),
    ]
